import { GeistSans } from 'geist/font/sans'
import type { Metadata } from 'next'
import './globals.css'
import MainNav from './components/main-nav'

export const metadata: Metadata = {
  title: 'Wanderlust | Assistants',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <MainNav />
        <main className='h-[calc(100vh-57px)]'>
          {children}
        </main>
      </body>
    </html>
  )
}
